### PR TITLE
docs(sdk): update python-crypto api-documentation

### PR DESCRIPTION
**Pull request by osrn**
api-documentation updated to align with the python-crypto library (#28).
revised/added/removed/reordered function and parameter descriptions.

### CODE REVIEW

**Comment by c0nsol3** [comment]
I think this looks ok. I've added `set_fee` to the `builder.base.py` as well: https://github.com/Solar-network/python-crypto/blob/master/solar_crypto/transactions/builder/base.py#L101-L102

**Comment by osrn** [comment]
Thanks for reviewing. I can add the missing set_fee to the docs tomorrow if that's ok.

**Comment by sleepdefic1t** [comment]
Thank you for reviewing, @c0nsol3!!

And thank you, @osrn!
We'll be on the lookout for the `set_fee` commit 👍

**Review by sleepdefic1t — APPROVED** [review]

**Comment by alessiodf** [comment]
Thank you @osrn :)

**Pull request merged**
